[package]
name = "mewo_ecs_derive"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/davnotdev/mewo"
homepage = "https://github.com/davnotdev/mewo"
license = "BSD-2-Clause"
keywords = ["gamedev", "game", "ecs"]

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
